# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-20.04"
NODE_COUNT_LOADBALANCER = 1
NODE_COUNT_WEBSERVER = 2


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
  end
  (1..NODE_COUNT_LOADBALANCER).each do |i|
    config.vm.define "loadbalancer-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "loadbalancer-#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"

    end
  end

  (1..NODE_COUNT_WEBSERVER).each do |i|
    config.vm.define "webserver-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "webserver-#{i}"
      subconfig.vm.network :private_network, ip: "10.0.1.#{i + 10}"

    end
  end



end

