- name: Docker-compose | copy docker-compose directory
  copy: 
    src: "{{ docker_compose__projects[item].src}}" 
    dest: "{{ docker_compose__projects[item].dest }}"
  with_items: "{{ docker_compose__projects | list }}"
  

- name: Docker-compose | run docker compose
  community.docker.docker_compose:
     project_src: "{{ docker_compose__projects[item].dest }}/{{ docker_compose__projects[item].project_name }}"
     state: "{{ docker_compose__projects[item].state }}"
     scale: 
       app: "{{ docker_compose__projects[item].scale_app }}"
  with_items: "{{ docker_compose__projects | list }}"
  register: docker_compose__debug_create
  when:  docker_compose__restart == "no"

- name: Docker-compose | debug creation
  debug: 
    var: docker_compose__debug_create
  when: docker_compose__debug 

- name: Docker-compose | Restart services
  community.docker.docker_compose:
    project_src: "{{ docker_compose__projects[item].dest }}/{{ docker_compose__projects[item].project_name }}"
    build: no
    restarted: yes
  with_items: "{{ docker_compose__projects | list }}"
  register: docker_compose__debug_restart
  when:  docker_compose__restart == "yes"

- name: Docker-compose | debug restart
  debug: 
    var: docker_compose__debug_restart
  when: docker_compose__debug 