version: '3.6'

services:
  haproxy:
    image: haproxy:1.3
    build: 
      context: ./
    restart: always  
    ports:
      - '80:80'
      - '127.0.0.1:1936:1936'
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
