docker_compose__debug: ""
docker_compose__restart: "no"
docker_compose__projects:
  webserver:
    project_name: service
    src: servis
    dest: /opt/docker-compose/
    scale_app: 1
    state: "present"
